### ISSUE TITLE
Class 'NotificationChannels\Discord\DiscordServiceProvider' not found

### ISSUE THREAD

**Issue by YumiAlmero03** [laravel-notification-channels/discord#13]
Hi

i am trying your package and i cant proceed in setting up the discord bot cause i keep receiving this error in my php artisan...

[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'NotificationChannels\Discord\DiscordServiceProvider' not found

i have put this in app.php
NotificationChannels\Discord\DiscordServiceProvider::class

thanks in advance :D

**Comment by codyphobe** [comment]
Did you add the service provider before or after you ran composer?

**Comment by YumiAlmero03** [comment]
yes i have

my error is i the package wasnt included in composer
my bad sorry

i have another question
i run this in my terminal: php artisan discord:setup
but i get an error:

```
[Symfony\Component\Console\Exception\CommandNotFoundException]
There are no commands defined in the "discord" namespace.
```

is there that i miss i also included in services,php
'discord' => [
        'token' => '<my token>',
    ],

**Comment by codyphobe** [comment]
Try removing all references to the package (i.e. the service provider in `app.php`), then re-install it with composer, add the service provider, and see if the command loads.

**Comment by YumiAlmero03** [comment]
still not working :(

**Comment by YumiAlmero03** [comment]
i have try it 2 times

**Comment by wast** [comment]
Status? Close?
