### ISSUE TITLE
Discord responded with an error while trying to identify the bot: 

### ISSUE THREAD

**Issue by rolandverner** [laravel-notification-channels/discord#16]
Not works

Attempting to identify the bot with Discord's websocket gateway...
Connecting to 'wss://gateway.discord.gg'...
Discord responded with an error while trying to identify the bot: {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["gateway-prd-main-3q62"]}}

NotificationChannels\Discord\Exceptions\CouldNotSendNotification with message 'Discord responded with an HTTP error: 400'

**Comment by codyphobe** [comment]
Thanks, fixed in [v1.0.3](https://github.com/laravel-notification-channels/discord/releases/tag/v1.0.3) although the bot should have been identified with the Discord gateway, they just changed the response a bit and broke the check. My bad for not checking the opcode in the first place 😞
