### ISSUE TITLE
Support for laravel 5.6

### ISSUE THREAD

**Issue by molteber** [laravel-notification-channels/discord#18]
Hi, when will you release support for laravel 5.6?

**Comment by codyphobe** [comment]
I'm in a bit of a hurry so I had to remove support for older versions but [v1.0.4](https://github.com/laravel-notification-channels/discord/releases/tag/v1.0.4) adds support for 5.6.

I'd accept a pull request if anyone wants to take the time to add support for older versions without breaking the tests (I kept running into version issues and API changes in PHPUnit/Orchestra)
