### ISSUE TITLE
Release new version for Laravel 5.8

### ISSUE THREAD

**Issue by MrBMT** [laravel-notification-channels/discord#23]
I just rolled out a new Laravel app and wanted to add discord notifications support, went to install the package and simply running `composer require laravel-notification-channels/discord` results in the package [failing to install](https://gist.github.com/MrBMT/3ea8e4b0f8b59df6bdd45cb9308be5d1) due to the illuminate/queue requirements.

As 5.8 support was recently added in https://github.com/laravel-notification-channels/discord/commit/397a25b295214fd7b20de5852773b0e4023d79f6 could you publish a new release to support this officially?

In the meanwhile as a workaround for anyone else experiencing this, you can use `composer require laravel-notification-channels/discord:dev-master` to install it.

**Comment by codyphobe** [comment]
Done. Sorry about that, I always forget to publish a new release.
