### ISSUE TITLE
Support for Laravel 6

### ISSUE THREAD

**Issue by wast** [laravel-notification-channels/discord#29]
Hi, when can we expect support for Laravel 6?

I guess this will work https://github.com/laravel-notification-channels/discord/pull/28

**Comment by vpratfr** [comment]
Hi,

I see that the PR for 6.0 support has been merged. Any plan to make a release soon?

**Comment by Diddyy** [comment]
Support seems to have been made for 6.0 like @vpratfr has asked, any plans to release this soon?

**Comment by xperator** [comment]
Yeah I'm also looking forward for a release. Need that `6.0` support.

**Comment by atymic** [comment]
See this issue. I can't fix it myself as I don't have packagist access :(
https://github.com/laravel-notification-channels/laravel-notification-channels.github.io/issues/25

**Comment by codyphobe** [comment]
Sorry about that, guys, been away from my computer lately. As for Packagist, it should automatically trigger new versions on a new release. I know I had to update it myself when Packagist migrated to the new system, so this repo should be fine.

**Comment by atymic** [comment]
Github hooks should be syncing with packagist properly now. If there are any issues in the future ping me 😄
