### ISSUE TITLE
HTTP error: 403: Cannot send messages to this user

### ISSUE THREAD

**Issue by Qirel** [laravel-notification-channels/discord#35]
I'm getting the following message, 

> Line 24 in [...]/vendor/laravel-notification-channels/discord/src/Exceptions/CouldNotSendNotification.php- Discord responded with an HTTP error: 403: Cannot send messages to this user

But I am unable to figure out how to catch this exception and handle it accordingly. The issue here is that the Discord bot no longer has any channels in common with that particular user, so its unable to send that PM - which makes sense. 

How can I catch these exceptions from inside the Notification itself? It's sent to a few different users, not individually, so catching the `Notification::send()` method is not an option.

**Comment by spinalwiz** [comment]
I think this is still an issue as if you are sending to multiple channels (e.g. 'mail' and 'database') then this exception will prevent it being sent to these other channels.
