### ISSUE TITLE
Laravel 9 Compatibility

### ISSUE THREAD

**Issue by FallenKnight85** [laravel-notification-channels/discord#55]
I tried updating to Laravel 9 but having conflicts with

illuminate/queue and laravel/framework packages.

`Only one of these can be installed: illuminate/queue[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/queue and thus cannot coexist with it.`

**Comment by ipkpjersi** [comment]
The fix is in #54 it just needs to be merged by someone with access.

**Comment by atymic** [comment]
Fixed :)
