### ISSUE TITLE
Driver not supported

### ISSUE THREAD

**Issue by Smashmint** [laravel-notification-channels/discord#6]
I followed the installation procedure but with my first try sending a notification i get the following error:

`InvalidArgumentException in Manager.php line 90:
Driver [App\Notifications\DiscordChannel] not supported.`

**Comment by codyphobe** [comment]
It looks like you haven't imported `NotificationChannels\Discord\DiscordChannel` class in your notification class.

**Comment by Smashmint** [comment]
Thanks, all working now :)
