### ISSUE TITLE
Embed objects

### ISSUE THREAD

**Issue by xHeinrich** [laravel-notification-channels/discord#7]
Does anybody have an updated version of this that supports embed objects as seen in the docs here: https://discordapp.com/developers/docs/resources/channel#embed-object

Supports message formats that look like so: https://i.gyazo.com/6033ee0a7432f806218931babb418f1b.png

If not I will create a pull request.

**Comment by codyphobe** [comment]
Unfortunately, I've been without a computer for quite a while and haven't been able to work on anything. I should have time to work on this soon unless you have a PR ready to go.
